pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                def devData = readYaml file: 'dev.yml' 
                def serviceAccountName = devData.service-account-name
                echo "Building.. ${serviceAccountName}"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
