node {
  stage('test-file-parameter') {
        def devData = readYaml file: 'templates/test-template/template.yaml'
        def serviceAccountName = devData.name
        println "Hello World. ${serviceAccountName}"
  }
}
